service: laconia-examples-serverless-websocket

provider:
  name: aws
  runtime: nodejs10.x
  region: ${opt:region, 'eu-west-1'}

functions:
  connectionHandler:
    handler: handler.connect
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect

  defaultHandler:
    handler: handler.message
    events:
      - websocket: $default
